[project]
name = 'Decentralized-Healthcare-Interoperability-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consent-management]
path = 'contracts/consent-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.data-standadization]
path = 'contracts/data-standadization.clar'
clarity_version = 2
epoch = 2.5

[contracts.patient-identity]
path = 'contracts/patient-identity.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
